# BoTorch-MODEL

In [1]:
DATA = "march_nsgp" # or "prev"

- python train.py [Fold] [Kernel] [Random_state] [DATA] 

- python test.py [Fold] [Kernel] [Best-Model-Path] [DATA] 


# RBF

In [2]:
for i in range(10):
    !python train_ngpu.py 0 rbf {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:53<00:00,  7.43it/s]
Loss:  41.55955505371094
RMSE:  25.82422764106294
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:54<00:00,  7.32it/s]
Loss:  57.43497085571289
RMSE:  25.808171148286824
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:54<00:00,  7.34it/s]
Loss:  48.816162109375
RMSE:  25.676222221986468
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:54<00:00,  7.40it/s]
Loss:  48.859222412109375
RMSE:  25.610424185344673
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:53<00:00,  7.43it/s]
Loss:  69.66155242

In [3]:
for i in range(10):
    !python train.py 1 rbf {i} {DATA}

Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytorch'
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytorch'
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytorch'
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytor

In [4]:
for i in range(10):
    !python train.py 2 rbf {i} {DATA}

Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytorch'
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytorch'
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytorch'
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train.py", line 9, in <module>
    from early_stopping_pytorch.pytorchtools import EarlyStopping
ModuleNotFoundError: No module named 'early_stopping_pytor

# Matern12

In [5]:
for i in range(1):
    !python train_ngpu.py 0 matern12 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:56<00:00,  7.13it/s]
Loss:  31.894268035888672
RMSE:  25.095991597355848


In [6]:
for i in range(1):
    !python train_ngpu.py 1 matern12 {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:57<00:00,  6.96it/s]
Loss:  32.59128952026367
RMSE:  24.613468752277736


In [7]:
for i in range(1):
    !python train_ngpu.py 2 matern12 {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
 79%|████████████████████████████████▎        | 315/400 [00:44<00:11,  7.16it/s]EarlyStopping counter: 5 out of 5
Early stopping
 79%|████████████████████████████████▎        | 315/400 [00:44<00:11,  7.11it/s]
Loss:  32.45455551147461
RMSE:  32.38366432605311


# Matern32

In [8]:
for i in range(10):
    !python train_ngpu.py 0 matern32 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [01:05<00:00,  6.10it/s]
Loss:  35.19859313964844
RMSE:  24.99610049784973
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:57<00:00,  6.91it/s]
Loss:  53.9440803527832
RMSE:  25.300447572158607
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:57<00:00,  6.92it/s]
Loss:  44.85477066040039
RMSE:  25.04567375978869
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:57<00:00,  6.93it/s]
Loss:  45.85558319091797
RMSE:  25.120809641420838
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:57<00:00,  6.95it/s]
Loss:  60.891201019

In [9]:
for i in range(10):
    !python train_ngpu.py 1 matern32 {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [00:59<00:00,  6.67it/s]
Loss:  35.679420471191406
RMSE:  25.00042429463852


In [ ]:
for i in range(10):
    !python train_ngpu.py 2 matern32 {i} {DATA}

Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9, in <module>
    from .early_stopping_pytorch.pytorchtools import EarlyStopping
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9, in <module>
    from .early_stopping_pytorch.pytorchtools import EarlyStopping
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9, in <module>
    from .early_stopping_pytorch.pytorchtools import EarlyStopping
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9, in <module>
    from .early_stopping_pytorch.pytorchtools import EarlyStopping
ImportError: att

# Matern52

In [ ]:
for i in range(10):
    !python train_ngpu.py 0 matern52 {i} {DATA}

  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_

In [ ]:
for i in range(10):
    !python train_ngpu.py 1 matern52 {i} {DATA}

  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_

In [ ]:
for i in range(10):
    !python train_ngpu.py 2 matern52 {i} {DATA}

  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_

# Matern+Rbf

In [ ]:
for i in range(10):
    !python train_ngpu.py 0 matern_rbf {i} {DATA}

  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_

In [ ]:
for i in range(10):
    !python train_ngpu.py 1 matern_rbf {i} {DATA}

  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_

In [ ]:
for i in range(10):
    !python train_ngpu.py 2 matern_rbf {i} {DATA}

  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_gp_cat/train_ngpu.py", line 9
    from early-stopping-pytorch.pytorchtools import EarlyStopping
              ^
SyntaxError: invalid syntax
  File "/home/sachin.yadav/DeepGP-ML-Project/stat_

In [ ]:
python train_ngpu.py 2 matern_rbf 9 {DATA}

SyntaxError: invalid syntax (615251177.py, line 1)

# Matern*Rbf

In [ ]:
for i in range(10):
    !python train_ngpu.py 0 maternXrbf {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:38<00:00,  2.52it/s]
Loss:  44.44075012207031
RMSE:  23.379183511435922
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:39<00:00,  2.51it/s]
Loss:  79.08614349365234
RMSE:  24.689282126434374
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:39<00:00,  2.50it/s]
Loss:  60.159793853759766
RMSE:  23.887044191944817
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  67.19532775878906
RMSE:  24.7487533550321
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  81.2378845

In [ ]:
for i in range(10):
    !python train_ngpu.py 1 maternXrbf {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  45.33794021606445
RMSE:  28.426958249880503
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:39<00:00,  2.50it/s]
Loss:  81.917724609375
RMSE:  29.24371284215504
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.53it/s]
Loss:  61.95417404174805
RMSE:  27.62149806585598
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:40<00:00,  2.49it/s]
Loss:  68.59915924072266
RMSE:  28.778987724130857
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.40it/s]
Loss:  83.1987075805

In [ ]:
for i in range(10):
    !python train_ngpu.py 2 maternXrbf {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  43.53270721435547
RMSE:  25.984832241605186
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  79.22278594970703
RMSE:  27.30191169882525
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:40<00:00,  2.49it/s]
Loss:  59.454830169677734
RMSE:  26.461402619542223
Fold:  2
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  66.42056274414062
RMSE:  27.08966083880808
Fold:  2
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  79.9538650

# TESTING

In [ ]:
kernel = "rbf"
RS = 0
for fold in [0,1,2]:
    !python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

Fold:  0
RMSE:  23.11186673126866
Saving to:  final_preds/march_nsgp_data/rbf_fold_0.csv.gz
Fold:  1
RMSE:  64.45875871446353
Saving to:  final_preds/march_nsgp_data/rbf_fold_1.csv.gz
Fold:  2
RMSE:  58.63771661695074
Saving to:  final_preds/march_nsgp_data/rbf_fold_2.csv.gz


In [ ]:
kernel = "local_p_matern12"
RS = 0
fold = 0
!python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

Fold:  0
RMSE:  22.665243962608265
Parameter containing:
tensor([[0.5429]], device='cuda:0', requires_grad=True)
[Parameter containing:
tensor([7.0897], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.7093], device='cuda:0', requires_grad=True), Parameter containing:
tensor(7.6226, device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 1.4876,  1.1397,  1.9450,  4.0049,  2.9279, -0.5051]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-4.0086]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[0.5429]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[2.9021, 6.0797]], device='cuda:0', requires_grad=True)]


In [ ]:
kernel = "matern12"
RS = 0
fold = 0
!python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

Fold:  0
RMSE:  22.886925750497763
{}
{}


In [ ]:
# LOCALLY PERIODIC KERNEL
for i in range(1):
    !python train_ngpu.py 0 local_p {i} {DATA}

['longitude', 'latitude', 'weather', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'delta_t']
Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:23<00:00,  2.79it/s]
Loss:  35.50748062133789
RMSE:  22.047243425624018


In [ ]:
for i in range(5):
    !python train_ngpu.py 1 local_p {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:25<00:00,  2.75it/s]
Loss:  35.15379333496094
RMSE:  27.14657898922616
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:26<00:00,  2.74it/s]
Loss:  51.49993133544922
RMSE:  26.666307813739582
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:30<00:00,  2.66it/s]
Loss:  44.41213607788086
RMSE:  26.6582895510393
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:27<00:00,  2.70it/s]
Loss:  45.4356803894043
RMSE:  26.413755022761187
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:27<00:00,  2.72it/s]
Loss:  62.5826683044

In [ ]:
for i in range(1):
    !python train_ngpu.py 2 local_p {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:28<00:00,  2.69it/s]
Loss:  34.28480529785156
RMSE:  24.838663679298914


In [ ]:
# LOCALLY PERIODIC KERNEL with Matern12
for i in range(1):
    !python train_ngpu.py 0 local_p_matern12 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:34<00:00,  2.58it/s]
Loss:  29.012474060058594
RMSE:  22.665243962608265


In [ ]:
for i in range(1):
    !python train_ngpu.py 1 local_p_matern12 {i} {DATA}

['longitude', 'latitude', 'weather', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'delta_t']
Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:32<00:00,  2.63it/s]
Loss:  29.42738151550293
RMSE:  25.300777724021412


In [ ]:
for i in range(1):
    !python train_ngpu.py 2 local_p_matern12 {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:35<00:00,  2.57it/s]
Loss:  28.327442169189453
RMSE:  25.614186786696035


In [ ]:
kernel = "matern12"
RS = 0
for fold in [0]:
    !python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

['longitude', 'latitude', 'weather', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'delta_t']
Fold:  0
RMSE:  22.235481166953427


In [ ]:
for i in range(3):
    !python train_ngpu.py 1 local_p_with_rbf {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  34.33063507080078
RMSE:  27.08063556447951
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  55.41059875488281
RMSE:  26.472000784492145
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  47.88109588623047
RMSE:  26.905664428910168


In [ ]:
for i in range(3):
    !python train_ngpu.py 2 local_p_with_rbf {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:38<00:00,  2.52it/s]
Loss:  33.14033126831055
RMSE:  24.86097035648703
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  54.99959945678711
RMSE:  25.03040928379786
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  46.791255950927734
RMSE:  24.90465858341698


In [ ]:
for fold in range(3):
    for i in range(1):
        !python train_ngpu.py {fold} local_p_with_matern12 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  28.90599822998047
RMSE:  22.60155159178252
Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  28.984880447387695
RMSE:  24.955686423362916
Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.41it/s]
Loss:  27.846054077148438
RMSE:  25.26945400952628


In [ ]:
for fold in range(3):
    for i in range(5,7):
        !python train_ngpu.py {fold} local_p_with_matern12 {i} {DATA}

Fold:  0
Random State:  5
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.40it/s]
Loss:  45.038883209228516
RMSE:  22.978661861012085
Fold:  0
Random State:  6
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.40it/s]
Loss:  40.59265899658203
RMSE:  22.906740617732225
Fold:  1
Random State:  5
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  44.9982795715332
RMSE:  25.189961656136898
Fold:  1
Random State:  6
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  40.341461181640625
RMSE:  25.248299567103917
Fold:  2
Random State:  5
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.41it/s]
Loss:  44.70574

In [ ]:
kernel = "local_p_with_matern12"
RS = 0
fold = 0
!python test_ngpu.py 0 local_p_with_matern12 /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/local_p_with_matern12_fold_0_random_state_0 march_nsgp

Fold:  0
RMSE:  22.60155159178252
Saving to:  final_preds/march_nsgp_data/local_p_with_matern12_fold_0.csv.gz
